name: MSYS2
on: [push, pull_request]

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-libc++
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          mkdir .build
          g++ oxoInCPP/*.cpp -o .build/oxoByAxel.exe
      - uses: actions/upload-artifact@v3
        with:
          name: oxoByAxel.exe
          path: .build/oxoByAxel.exe
          
      - uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
