name: MSYS2
on: [push, pull_request]

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-libc++
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          mkdir .build
          g++ ticTacToeInCPP/*.cpp -o .build/ticTacToeByAxel.exe
      - name: Get-DLL
        run: |
          # Written by Axel.
          ldd .build/*|grep -iv system32|grep -vi windows|grep -v :$  | cut -f2 -d\> | cut -f1 -d\( | tr \\ / |while read a; do ! [ -e ".build/`basename $a`" ] && cp -v "$a" .build/; done
      - uses: actions/upload-artifact@v3
        with:
          name: ticTacToeByAxel.zip
          path: .build/
